language: java

addons:
  sonarcloud:
    organization: "lotreal-github"
    token:
      secure: $SONAR_TOKEN

script:
  - ./gradlew build --scan -s

deploy:
 provider: heroku
 api-key:
  secure: $HEROKU_API_KEY
 app: nho-workshop
